config/routes.rb
Rails.application.routes.draw do

  resources :ingredients, only: %i[index new create]
  # get 'ingredients', to: 'ingredients#index'
  # get 'ingredients/new', to: 'ingredients#new'

  get 'doses/new'
  # Ingredients Routes
  # get 'ingredients/:id/edit', to: 'ingredients#edit'
  # post 'ingredients', to: 'ingredients#create'
  # patch 'ingredients', to: 'ingredients#update'
  # delete 'ingredients', to: 'ingredients#delete'
  # get 'ingredients/:id', to: 'ingredients#show'

  # Cocktails routes
  # get 'cocktails', to: 'cocktails#index'
  # get 'cocktails/new', to: 'cocktails#new', as: 'cocktails_new'
  # get 'cocktails/:id', to: 'cocktails#show', as: 'cocktails_show'
  # post 'cocktails', to: 'cocktails#create'

  resources :cocktails, only: [:create, :index, :show, :new] do
    resources :doses, only: [:new, :create, :delete]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new
    @cocktail.update(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new
    @dose.update(dose_params)

    if @dose.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new
    @ingredient.update(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  # def show
  # end

  def index
    @ingredients = Ingredient.all
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<%= link_to 'New Cocktail', new_cocktail_path, class: "btn btn-primary" %>

<%= link_to 'Ingredients List', ingredients_path, class: "btn btn-primary" %>

<h1>Cocktails List</h1>

  <% @cocktails.each do |cocktail| %>
      <%= cocktail.name %>
      <br>
    <ul>
      <% cocktail.ingredients.each do |ingre| %>
        <li>
          <%= ingre.name %>
          <br>
        </li>
      <% end %>
      <%= link_to "Show", cocktail_path(cocktail) %>
    </ul>
  <% end %>

<%#= cl_image_tag("iyqqausv83krcffalppf", width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%#= cl_image_tag("v5jkxb4zysqyz4hgey2f", width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/cocktails/new.html.erb
<h1>Add cocktail</h1>

<%= simple_form_for @cocktail do |c| %>
  <%= c.input :name %>
  <%= c.input :photo, as: :file %>
  <%= c.button :submit , class: "btn btn-primary"%>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<p>
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
       <%= dose.ingredient.name %> | <%= dose.description %>
      </li>
    <% end %>
  </ul>
  <% if @cocktail.photo.attached? %>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
</p>
<%= link_to 'Back to Cocktails list', cocktails_path, class: "btn btn-primary" %>
<%= link_to 'New Dose', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>

app/views/doses/new.html.erb
<h1>Add Doses</h1>

<%= simple_form_for @dose, url: cocktail_doses_path do |f| %>
  <%= f.input :description %>
  <%= f.association :cocktail, input_html: { class: 'select2' } %>
  <%= f.association :ingredient, input_html: { class: 'select2' } %>
  <%= f.button :submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<%= link_to "Add an Ingredient", new_ingredient_path, class: "btn btn-primary" %>
<%= link_to 'Back to Cocktails list', cocktails_path, class: "btn btn-primary" %>
<h1>Ingredients</h1>
<ul>
  <% @ingredients.each do |ingredient| %>
  <li>
    <%= ingredient.name %>
  </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>Add ingredient</h1>

<%= simple_form_for @ingredient do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>